version: '3.8'

x-zaakbrug-postgres-env:
  environment: &zaakbrug-postgres-env
    POSTGRES_USER: zaakbrug
    POSTGRES_PASSWORD: zaakbrug
    POSTGRES_DB: zaakbrug

services:
  zaakbrug-postgres:
    image: postgres:${POSTGRES_VERSION:-14}
    environment: 
      <<: *zaakbrug-postgres-env
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5400:5432
    networks:
      - zaakbrug-backend
    volumes:
      - zaakbrug-postgres-data:/var/lib/postgresql/data
  
  zaakbrug-pgadmin:
    profiles:
      - pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    user: root
    command: ["/venv/bin/python3", "/pgadmin4/setup.py", "--load-servers", "zaakbrug-pgadmin-conf.json", "--user", "admin@wearefrank.nl"]
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wearefrank.nl
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - zaakbrug-stack
      - zaakbrug-backend
    depends_on:
      - zaakbrug-postgres

  zaakbrug:
    environment: 
      <<: *zaakbrug-postgres-env
      DB_HOSTNAME: zaakbrug-postgres
      DB_PORT: 5432
    volumes:
      - C:/Projects/zaakbrug/docker/zaakbrug-postgres/context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml:rw
    depends_on:
      - zaakbrug-postgres

volumes:
  zaakbrug-postgres-data:
