version: '3.8'

services:
  open-zaak-redis:
    image: redis
    networks:
      - open-zaak-backend

  open-zaak-db:
    image: mdillon/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/open-zaak-db/postgres.entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - open-zaak-db:/var/lib/postgresql/data
    networks:
      - open-zaak-backend
      - zaakbrug-stack
    ports:
      - 5432

  open-zaak:
    image: openzaak/open-zaak:1.10.3
    container_name: open-zaak.dev
    environment: &open-zaak-env
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - OPENZAAK_DOMAIN=open-zaak.dev:8000
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=openzaak
      - DB_USER=openzaak
      - DB_HOST=open-zaak-db
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=open-zaak-redis:6379/0
      - CACHE_AXES=open-zaak-redis:6379/0
      - SUBPATH=${SUBPATH:-/}
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@localhost
      - CELERY_BROKER_URL=redis://open-zaak-redis:6379/1
      - CELERY_RESULT_BACKEND=redis://open-zaak-redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
      # - SENDFILE_BACKEND=django_sendfile.backends.simple
      - SENDFILE_BACKEND=django_sendfile.backends.nginx
      - SENDFILE_ROOT=/app/private_media
      - SENDFILE_URL=/private-media/
      - NOTIFICATIONS_DISABLED=yes
      - DEBUG=1
      - LOG_LEVEL=DEBUG
      - LOG_QUERIES=false
    networks:
      - open-zaak-backend
    ports:
      - 8000
    volumes: &open-zaak-volumes
      - open-zaak-media:/app/media
      - open-zaak-private-media:/app/private-media
      - ./docker/open-zaak:/app/fixtures
    depends_on:
      - open-zaak-db
      - open-zaak-redis

  open-zaak-celery:
    image: openzaak/open-zaak:1.10.3
    environment: *open-zaak-env
    command: /celery_worker.sh
    volumes: *open-zaak-volumes
    networks:
      - open-zaak-backend
    depends_on:
      - open-zaak-db
      - open-zaak-redis

  open-zaak-celery-flower:
    image: openzaak/open-zaak:1.10.3
    environment: *open-zaak-env
    command: /celery_flower.sh
    networks:
      - open-zaak-backend
    ports:
      - 5555
    depends_on:
      - open-zaak-redis
      - open-zaak-celery

  open-zaak-nginx:
    image: nginx
    container_name: open-zaak.nginx
    volumes:
      - ./docker/open-zaak-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - open-zaak-private-media:/private-media
    networks:
      - zaakbrug-stack
      - open-zaak-backend
    ports:
      - 9001:9001
    depends_on:
      - open-zaak

  nginx:
    image: nginx
    volumes:
      - ./docker/open-zaak-nginx/openzaak.conf:/etc/nginx/includes/openzaak.conf
    networks:
      - open-zaak-backend
    ports:
      - 9000:9000
    depends_on:
      - open-zaak

  zaakbrug:
    environment:
      - zaakbrug.zgw.zaken-api.root-url=http://open-zaak.nginx:9001/zaken/api/v1/
      - zaakbrug.zgw.documenten-api.root-url=http://open-zaak.nginx:9001/documenten/api/v1/
      - zaakbrug.zgw.catalogi-api.root-url=http://open-zaak.nginx:9001/catalogi/api/v1/
      - zaakbrug.zgw.besluiten-api.root-url=http://open-zaak.nginx:9001/besluiten/api/v1/

volumes:
  open-zaak-db:
  open-zaak-media:
  open-zaak-private-media:

networks:
  zaakbrug-stack:
  open-zaak-backend:
