version: '4'

services:
  open-forms-db:
    image: postgres:${PG_VERSION:-14}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/open-forms-db/docker-entrypoint-initdb.d/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
      - open-forms-db:/var/lib/postgresql/data
    networks:
      - open-forms-backend

  open-forms-redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - open-forms-backend
    volumes:
      - open-forms-data:/data

  smtp:
    image: namshi/smtp
    networks:
      - open-forms-backend

  clamav:
    image: clamav/clamav:1.0.0
    networks:
      - open-forms-backend

  busybox:
    image: busybox
    command: /bin/chown -R 1000 /private-media
    volumes:
      - open-forms-private-media:/private-media
    networks:
      - open-forms-backend

  open-forms:
    image: openformulieren/open-forms:${TAG:-latest}
    container_name: open-forms.dev
    environment: &open-forms-env
      - DJANGO_SETTINGS_MODULE=openforms.conf.docker
      - SECRET_KEY=${SECRET_KEY:-@r0w-0(&apjfde5fl6h23!vn)r1ldkp1c_d2#!$$did4z5hun4a}
      - DB_NAME=openforms
      - DB_USER=openforms
      - DB_HOST=open-forms-db
      - CACHE_DEFAULT=open-forms-redis:6379/0
      - CACHE_AXES=open-forms-redis:6379/0
      - CACHE_OIDC=open-forms-redis:6379/0
      - CACHE_PORTALOCKER=open-forms-redis:6379/0
      - ALLOWED_HOSTS=*
      - CELERY_BROKER_URL=redis://open-forms-redis:6379/0
      - CELERY_RESULT_BACKEND=redis://open-forms-redis:6379/0
      - CELERY_LOGLEVEL=DEBUG
      - OPENFORMS_LOCATION_CLIENT=${OPENFORMS_LOCATION_CLIENT:-openforms.contrib.bag.client.BAGClient}
      - TWO_FACTOR_FORCE_OTP_ADMIN=0
      - TWO_FACTOR_PATCH_ADMIN=0
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS:-true}
      - EMAIL_HOST=smtp
      # Needed for Celery Flower to match the TIME_ZONE configured in the
      # settings used by workers and beat containers.
      - TZ=Europe/Amsterdam
      - CSP_REPORT_ONLY=yes
    volumes: &open-forms-volumes
      - open-forms-media:/app/media
      - open-forms-private-media:/app/private-media
      - open-forms-log:/app/log
      - certifi_ca_bundle:/app/certifi_ca_bundle
    ports:
      - 8000
    depends_on:
      - open-forms-db
      - open-forms-redis
      - smtp
      - clamav
    networks:
      - open-forms-backend

  open-forms-nginx:
    image: nginx
    container_name: open-forms.nginx
    volumes:
      - ./docker/open-forms-nginx/default.conf:/etc/nginx/includes/default.conf
      - open-forms-private-media:/private-media
    ports:
      - 9003:9003
    depends_on:
      - open-forms
    networks:
      - open-forms
      - open-forms-backend
  nginx:
    image: nginx
    volumes:
      - ./docker/open-forms-nginx/openforms.conf:/etc/nginx/includes/openforms.conf
    ports:
      - 9000:9000
    depends_on:
      - open-forms
    networks:
      - open-forms-backend

  open-forms-celery:
    image: openformulieren/open-forms:${TAG:-latest}
    environment: *open-forms-env
    command: /celery_worker.sh
    volumes: *open-forms-volumes
    depends_on:
      - open-forms-db
      - open-forms-redis
    networks:
      - open-forms-backend

  open-forms-celery-beat:
    image: openformulieren/open-forms:${TAG:-latest}
    environment: *open-forms-env
    command: /celery_beat.sh
    depends_on:
      - open-forms-db
      - open-forms-redis
    networks:
      - open-forms-backend

  open-forms-celery-flower:
    image: openformulieren/open-forms:${TAG:-latest}
    environment: *open-forms-env
    command: /celery_flower.sh
    ports:
      - 5555
    depends_on:
      - open-forms-redis
      - open-forms-celery
    networks:
      - open-forms-backend

volumes:
  open-forms-db:
  open-forms-media:
  open-forms-private-media:
  open-forms-log:
  certifi_ca_bundle:
  open-forms-data:

networks:
  open-forms:
    name: zaakbrug-stack
  open-forms-backend: