version: '3.8'

services:
  zaakbrug-staging-redis:
    image: redis
    networks:
      - zaakbrug-backend

  zaakbrug-staging-db:
    image: mdillon/postgis
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/zaakbrug-staging-db/postgres.entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - zaakbrug-staging-db:/var/lib/postgresql/data
    networks:
      - zaakbrug-backend
    ports:
      - 5432

  zaakbrug-staging:
    image: openzaak/open-zaak:1.9.0
    container_name: zaakbrug.staging.dev
    environment: &zaakbrug-staging-env
      - DJANGO_SETTINGS_MODULE=openzaak.conf.docker
      - OPENZAAK_DOMAIN=host.docker.internal:9000
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=openzaak
      - DB_USER=openzaak
      - DB_HOST=zaakbrug-staging-db
      - IS_HTTPS=no
      - ALLOWED_HOSTS=*
      - CACHE_DEFAULT=zaakbrug-staging-redis:6379/0
      - CACHE_AXES=zaakbrug-staging-redis:6379/0
      - SUBPATH=${SUBPATH:-/}
      - OPENZAAK_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - OPENZAAK_SUPERUSER_EMAIL=admin@localhost
      - CELERY_BROKER_URL=redis://zaakbrug-staging-redis:6379/1
      - CELERY_RESULT_BACKEND=redis://zaakbrug-staging-redis:6379/1
      - CELERY_LOGLEVEL=DEBUG
      - CELERY_WORKER_CONCURRENCY=${CELERY_WORKER_CONCURRENCY:-4}
      # - SENDFILE_BACKEND=django_sendfile.backends.simple
      - SENDFILE_BACKEND=django_sendfile.backends.nginx
      - SENDFILE_ROOT=/app/private_media
      - SENDFILE_URL=/private-media/
      - NOTIFICATIONS_DISABLED=yes
      - DEBUG=1
      - LOG_LEVEL=DEBUG
      - LOG_QUERIES=true
      - USE_X_FORWARDED_HOST=False
    networks:
      - zaakbrug-backend
    ports:
      - 8000
    volumes: &zaakbrug-staging-volumes
      - zaakbrug-staging-media:/app/media
      - zaakbrug-staging-private-media:/app/private-media
    depends_on:
      - zaakbrug-staging-db
      - zaakbrug-staging-redis

  zaakbrug-staging-celery:
    image: openzaak/open-zaak:1.9.0
    environment: *zaakbrug-staging-env
    command: /celery_worker.sh
    volumes: *zaakbrug-staging-volumes
    networks:
      - zaakbrug-backend
    depends_on:
      - zaakbrug-staging-db
      - zaakbrug-staging-redis

  zaakbrug-staging-celery-flower:
    image: openzaak/open-zaak:1.9.0
    environment: *zaakbrug-staging-env
    command: /celery_flower.sh
    networks:
      - zaakbrug-backend
    ports:
      - 5555
    depends_on:
      - zaakbrug-staging-redis
      - zaakbrug-staging-celery

  zaakbrug-staging-nginx:
    image: nginx
    container_name: zaakbrug.staging.nginx
    volumes:
      - ./docker/zaakbrug-staging-nginx/default.conf:/etc/nginx/conf.d/default.conf
      - zaakbrug-staging-private-media:/private-media
    networks:
      - zaakbrug-backend
    ports:
      - 9002:9002
    depends_on:
      - zaakbrug-staging

  nginx:
    image: nginx
    volumes:
      - ./docker/zaakbrug-staging-nginx/zaakbrug-staging.conf:/etc/nginx/includes/zaakbrug-staging.conf
    networks:
      - zaakbrug-backend
    ports:
      - 9000:9000
    depends_on:
      - zaakbrug-staging

  zaakbrug:
    environment:
      - zaakbrug.staging.zaken-api.root-url=http://zaakbrug.staging.nginx:9002/zaken/api/v1/
      - zaakbrug.staging.documenten-api.root-url=http://zaakbrug.staging.nginx:9002/documenten/api/v1/
      - zaakbrug.staging.catalogi-api.root-url=http://zaakbrug.staging.nginx:9002/catalogi/api/v1/
      - zaakbrug.staging.besluiten-api.root-url=http://zaakbrug.staging.nginx:9002/besluiten/api/v1/

volumes:
  zaakbrug-staging-db:
  zaakbrug-staging-media:
  zaakbrug-staging-private-media:

networks:
  zaakbrug-stack:
  zaakbrug-backend:
